### ISSUE TITLE
[Bug] Separate Order Type and Bottle Type

### ISSUE THREAD

**Issue by mariamumoki99** [powwater/pow_vendor#101]
At the moment, the order types (refill, swap, new) are in the same list as the bottle types (dispenser bottle, jerrycan bottle, PET bottle) as demonstrated on the screenshot below. 

![Screenshot 2021-08-04 at 10 15 07](https://user-images.githubusercontent.com/77880053/128138187-ab3f111f-06f7-4fa2-bfda-18834757c9be.png)

The `order types` should be a separate list of options from the `bottle types` and should be separate drop downs.

**Comment by phoward38** [comment]
Fixed w/ #99 & #100
