### ISSUE TITLE
Inventory: Make simple check boxes instead of add/delete functionality

### ISSUE THREAD

**Issue by jimbrig** [powwater/pow_vendor#34]

**Comment by jimbrig** [comment]
Make a PR for this and submit to Andy for review

**Comment by merlinoa** [comment]
@jimbrig why is this onhold

**Comment by jimbrig** [comment]
@merlinoa because we are/were awaiting more details on the vendor's global possible offerings and whether to include refill options along with new and swap (which I discussed with Jack and Ellie yesterday and have a good handle on now).
