### ISSUE TITLE
Add bottle type to vendor portal’s inventory page.

### ISSUE THREAD

**Issue by imhilla** [powwater/pow_vendor#99]
- Add a Bottle Type drop down that will have the options: Dispenser Bottle , PET Bottle , Jerrycan Bottle.
-  The capacities that should be available going forward are: 10L , 18.9L , 20L .

**Comment by merlinoa** [comment]
updated and redeployed

**Comment by phoward38** [comment]
@merlinoa Each `Order Type` (Swap, New, Refill) can have any of the `Bottle Type` values, so we'll need to add an additional DB table column & picker input for `Bottle Type`

![image](https://user-images.githubusercontent.com/33097210/127559433-a61eef5d-b6a4-436b-98e0-601f58f78c4c.png)

**Comment by phoward38** [comment]
- PR for updating in `pow_vendor` app: https://github.com/powwater/pow_vendor/pull/100

**Comment by phoward38** [comment]
Completed
